# Generated by Django 3.2.6 on 2021-08-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_rater_api', '0002_rename_player_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
